services:
  db:
    image: postgres:16-alpine
    container_name: shelter_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shelter_db
      POSTGRES_USER: shelter_user
      POSTGRES_PASSWORD: "2112"
    ports:
      # Django в settings.py ожидает порт 5433 на localhost
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelter_web
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # В контейнерной сети хост БД — имя сервиса `db`
      POSTGRES_DB: shelter_db
      POSTGRES_USER: shelter_user
      POSTGRES_PASSWORD: "2112"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      USE_HTTPS: '1'
    ports:
      - "8000:8000"
    volumes:
      # Чтобы загруженные фото сохранялись на хосте
      - ./media:/app/media
      # Чтобы результат collectstatic сохранялся на хосте
      - ./staticfiles:/app/staticfiles

  caddy:
    image: caddy:2
    container_name: shelter_caddy
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/ssl:/etc/caddy/ssl:ro
      - caddy_data:/data
      - caddy_config:/config

  reminders:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelter_reminders
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_DB: shelter_db
      POSTGRES_USER: shelter_user
      POSTGRES_PASSWORD: "2112"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    command: ["sh", "-c", "python manage.py migrate && while true; do python manage.py send_reminders; sleep 86400; done"]

volumes:
  postgres_data:
