# Generated by Django 4.2.15 on 2026-04-27 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='Уникальный номер')),
                ('species', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('other', 'Другое')], max_length=10, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Неизвестно')], default='U', max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('approx_age', models.CharField(blank=True, max_length=50, verbose_name='Примерный возраст')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Окрас')),
                ('features', models.TextField(blank=True, verbose_name='Особые приметы')),
                ('intake_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('intake_source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('status', models.CharField(choices=[('intake', 'На приёме'), ('quarantine', 'Карантин'), ('healthy', 'Здоров'), ('treatment', 'Требует лечения'), ('ready', 'Готов к усыновлению'), ('adopted', 'Усыновлён'), ('deceased', 'Усыплён'), ('transferred', 'Передан')], default='intake', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'ordering': ['-intake_date'],
            },
        ),
        migrations.CreateModel(
            name='VetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('type', models.CharField(choices=[('exam', 'Осмотр'), ('vaccination', 'Вакцинация'), ('deworming', 'Дегельминтизация'), ('treatment', 'Лечение'), ('surgery', 'Операция'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vet_name', models.CharField(blank=True, max_length=100, verbose_name='Ветеринар')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='animals.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/%Y/%m/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='Откуда')),
                ('to_location', models.CharField(blank=True, max_length=100, verbose_name='Куда')),
                ('reason', models.CharField(choices=[('intake', 'Поступление'), ('transfer', 'Перемещение внутри приюта'), ('adoption', 'Усыновление'), ('death', 'Смерть'), ('handover', 'Передача другому приюту')], max_length=200, verbose_name='Причина')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='animals.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
