# Generated by Django 4.2.15 on 2026-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_name_photo_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Уникальный номер'),
        ),
    ]
